spring:
  web:
    resources:
      add-mappings: false
  config:
    activate:
      on-profile: dev
    import:
      - optional:file:.env[.properties]
  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            redirect-uri: ${DEV_BASE_URL}${OAUTH2_API_END_POINT}${GOOGLE_OAUTH2}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-name: Kakao
            provider: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: ${DEV_BASE_URL}${OAUTH2_API_END_POINT}${KAKAO_OAUTH2}
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET_KEY}

  access:
    expiration: 3600000
    header: Authorization

  refresh:
    expiration: 1209600000
    header: Authorization-refresh

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    s3:
      bucket: pollet-prod-bucket
    region:
      static: ap-northeast-2